### PR TITLE
Fix for amqp events

### PR DESCRIPTION
**Pull request by tzumainn**
Handles the case where the amqp message doesn't have the oslo.message key

https://bugzilla.redhat.com/show_bug.cgi?id=1451437

### CODE REVIEW

**Comment by mansam** [comment]
LGTM

**Comment by tzumainn** [comment]
Oh yeah! Fixed now - thanks!

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit 51599d545d8023ff34aeec57aa2bc54c71478ac9
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Wed Oct 25 16:19:40 2017 -0400

    Merge pull request #131 from tzumainn/amqp-event-fix
    
    Fix for amqp events
    (cherry picked from commit 438728f8bc924ca1b3254b5ea5038fa8b11df3ac)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1506626
```

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit 6d07c6f034f3f538968eb3232253f13835232217
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Wed Oct 25 16:19:40 2017 -0400

    Merge pull request #131 from tzumainn/amqp-event-fix
    
    Fix for amqp events
    (cherry picked from commit 438728f8bc924ca1b3254b5ea5038fa8b11df3ac)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1506624
```

**Pull request merged**
