### PR TITLE
update event parser code to deal with amqp messages

### PR DESCRIPTION
**Pull request by tzumainn**
https://bugzilla.redhat.com/show_bug.cgi?id=1451437

### CODE REVIEW

**Comment by tzumainn** [comment]
@aufi would it be possible to test this out? events aren't working in my openstack install for some reason

**Comment by tzumainn** [comment]
@aufi I managed to successfully test that events were parsed by manageiq; would you be able to verify on your setup?

**Comment by aufi** [comment]
@tzumainn Tested and works for me with Ceilometer Events, but does not work with AMQP Events.

There is an AMQP traffic going to OpenStack, so Event monitor works, but Timeline on provider are empty, unfortunately nothing significant in emv.log. I can provide acces to my env if needed.

**Comment by aufi** [comment]
@tzumainn AMQP Events don't work even without this PR, I don't consider it as issue for merging.

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit e4c69b7be214da2d41f7b0068b673c5f764c6f43
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Tue Oct 24 11:37:28 2017 -0400

    Merge pull request #127 from tzumainn/amqp-message-support
    
    update event parser code to deal with amqp messages
    (cherry picked from commit 3692df049bda7d0262e9ed2583d36f40a3baa3dd)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1506626
```

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit e1c93db89f827d6fdf031cbbc4c4f3fb29c2db39
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Tue Oct 24 11:37:28 2017 -0400

    Merge pull request #127 from tzumainn/amqp-message-support
    
    update event parser code to deal with amqp messages
    (cherry picked from commit 3692df049bda7d0262e9ed2583d36f40a3baa3dd)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1506624
```

**Pull request merged**
