### PR TITLE
Add configurable vhost to AMQP monitor

### PR DESCRIPTION
**Pull request by paulslaby**
We need to provide different vhost that default '/'. This commit adds the functionality to set it via Settings. 
It was already discussed @aufi.

### CODE REVIEW

**Comment by aufi** [comment]
Thanks for PR, looks good to me, merging :+1:

**Comment by aufi** [comment]
We'd need backport this to G-branch.

**Comment by aufi** [comment]
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1576457

**Comment by aufi** [comment]
G-branch BZ clone: https://bugzilla.redhat.com/show_bug.cgi?id=1591494

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 002de1a20157dba9a1fe3f77d441e40a2ec48045
Author: Marek Aufart <aufi.cz@gmail.com>
Date:   Fri Feb 2 13:13:20 2018 +0100

    Merge pull request #221 from paulslaby/master
    
    Add configurable vhost to AMQP monitor
    (cherry picked from commit 5f1c01e25b8d64b8c8c3f167ffd64f0242d7bfe2)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1591494
```

**Pull request merged**
