### PR TITLE
BZ 1635635 Avoid uniqueness constraint violations in sync_users

### PR DESCRIPTION
**Pull request by sseago**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1635635

Manual changes after prior sync could result in the auto-generated
MiqGroup name/description duplicating existing values. If the auto-
generated name results in a uniqueness constraint violation, use
a timestamped name instead.

### CODE REVIEW

**Comment by aufi** [comment]
Thanks for the PR @sseago, please make PR/commit name more descriptive (some text instead of just BZ number).

**Comment by simaishi** [comment]
@sseago @mansam `hammer/yes` and `gaprindashvili/yes` ?

**Comment by mansam** [comment]
@simaishi Yep, thanks!

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 59905573afe00e0311eb681fd3fe0ee2ab0f6e21
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Mon Oct 22 09:17:51 2018 -0400

    Merge pull request #373 from sseago/sync_users_unique_name
    
    BZ 1635635 Avoid uniqueness constraint violations in sync_users
    
    (cherry picked from commit d2eb365bff5b31c50b35d02cdc2775178840e37f)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1635635
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 19e8a0077f8346dac194830c63877a2645b2b099
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Mon Oct 22 09:17:51 2018 -0400

    Merge pull request #373 from sseago/sync_users_unique_name
    
    BZ 1635635 Avoid uniqueness constraint violations in sync_users
    
    (cherry picked from commit d2eb365bff5b31c50b35d02cdc2775178840e37f)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643539
```

**Pull request merged**
