### PR TITLE
Override az_zone_to_cloud_network in openstack prov

### PR DESCRIPTION
**Pull request by d-m-u**
I messed up [here](https://github.com/ManageIQ/manageiq-providers-openstack/pull/197) should be reverted because the [logic in main](https://github.com/ManageIQ/manageiq/blob/master/app/models/manageiq/providers/cloud_manager/provision_workflow.rb#L98) is wrong. That else case should not include cloud_subnets: fixed in https://github.com/ManageIQ/manageiq/pull/16824. Per [comment](https://github.com/ManageIQ/manageiq/pull/16824/files#r161679886) we need to override this method in google and openstack because the availability zone to subnet relationship isn't set up yet. 

Fixes issue caused by fix of https://bugzilla.redhat.com/show_bug.cgi?id=1533277
(Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1535189)

## Depends on:
https://github.com/ManageIQ/manageiq/pull/16824

## Related to:
https://github.com/ManageIQ/manageiq-providers-google/pull/43

### CODE REVIEW

**Comment by d-m-u** [comment]
@miq-bot assign @gmcculloug 
@miq-bot add_label bug
@miq-bot add_label blocker

**Comment by mansam** [comment]
So once this and https://github.com/ManageIQ/manageiq/pull/16824 are merged are we good, or is there another follow-up PR coming?

**Comment by d-m-u** [comment]
We have two more changes coming because both openstack and google need to override the def availability_zone_to_cloud_network(src) method that's in the main repo PR

**Comment by d-m-u** [comment]
@syncrou @gmcculloug can you two please give this (hopefully) a final look?

**Comment by d-m-u** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by d-m-u** [comment]
The test that's failing is expected because the call references a line that got changed in the linked main pr [here](https://github.com/ManageIQ/manageiq/pull/16824/files#diff-affc070fa31fb03b3d1afa85434e8f3dL30)

**Comment by d-m-u** [comment]
@mansam if you don't mind, I'd like GM to review before this has anything happen to it, please

**Comment by syncrou** [comment]
👍 - This looks good to me - understanding it can't go green until the PR from the main app is merged.

**Comment by gmcculloug** [comment]
@mansam Can you review?   This is a followup to PR https://github.com/ManageIQ/manageiq-providers-openstack/pull/197.

**Comment by d-m-u** [comment]
Kicked, but expecting to fail with https://travis-ci.org/ManageIQ/manageiq-providers-openstack/jobs/330414913#L2076 error because all of openstack is red at the moment

**Comment by d-m-u** [comment]
@miq-bot add_label gaprindashvili/yes

**Pull request merged**
