### PR TITLE
bz 1504131: For archived nodes, just delete AR object on remove

### PR DESCRIPTION
**Pull request by sseago**
https://bugzilla.redhat.com/show_bug.cgi?id=1504131

Archived nodes have no ems, so don't try to contact the (nonexistent) provider.
Just delete the AR object.

### CODE REVIEW

**Comment by mansam** [comment]
@miq-bot add_label fine/yes
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit ae06afcc2726ccf6a3c4d557dbb2c45f94679896
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Fri Jan 19 09:33:21 2018 -0500

    Merge pull request #165 from sseago/archived_host_destroy
    
    bz 1504131: For archived nodes, just delete AR object on remove
    (cherry picked from commit a4f598f4725d13104f88e0d8e4688822a787129e)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1554898
```

**Comment by simaishi** [comment]
@sseago There are some conflicts backporting to Fine branch. Please create a separate PR for Fine.

**Comment by sseago** [comment]
@simaishi https://github.com/ManageIQ/manageiq/pull/17286 for the fine branch

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq/pull/17286

**Pull request merged**
