### PR TITLE
Discovery namespace change

### PR DESCRIPTION
**Pull request by gildub**
Reflect change in Discovery core introduced in https://github.com/ManageIQ/manageiq/pull/16994.

### CODE REVIEW

**Comment by gildub** [comment]
@d-m-u, @kbrock could you please review ASAP in order to walk away from the dual name space collusion?

**Comment by gildub** [comment]
Not needed per existing https://github.com/ManageIQ/manageiq-providers-openstack/pull/227

**Comment by gildub** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
@gildub This PR is "Closed". Do we need to pick up something else for https://bugzilla.redhat.com/show_bug.cgi?id=1212947?

**Comment by gildub** [comment]
@miq-bot remove_label gaprindashvili/no

**Comment by gildub** [comment]
@miq-bot remove_label gaprindashvili/no

**Pull request closed without merging**
