### PR TITLE
Fog update 0.1.22

### PR DESCRIPTION
**Pull request by tzumainn**

### CODE REVIEW

**Comment by mansam** [comment]
huzzah!

**Comment by aufi** [comment]
@tzumainn @mansam Thanks for the PR and merge!

Missing ```:ipmi_address``` and ```:service_tag``` seem finally to be correct since it match to OpenStack CLI.

Adding fine/yes label since I think we want OpenStack Pike support also there.

**Comment by simaishi** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1508572

**Comment by simaishi** [comment]
@tzumainn There are lots of conflicts in spec. Can you please create a PR for Fine branch?

```
$ git status
On branch fine
Your branch is up-to-date with 'origin/fine'.
You are currently cherry-picking commit db7c57c.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Changes to be committed:

	modified:   spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by us:   manageiq-providers-openstack.gemspec
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_icehouse.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_icehouse_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_icehouse_legacy_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_juno.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_juno_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_juno_legacy_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_keystone_v3.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_keystone_v3_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_keystone_v3_legacy_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_legacy_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_with_errors.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/infra_manager/refresher_rhos_juno.yml
	both modified:   spec/vcr_cassettes/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_maintenance.yml
```

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq-gems-pending/pull/310

**Pull request merged**
