### PR TITLE
Ensure managers change zone and provider region with cloud manager

### PR DESCRIPTION
**Pull request by Ladas**
Depends on:
- [x] https://github.com/ManageIQ/manageiq/pull/14741

Ensure managers change zone and provider region with cloud manager

The bug occurs when Cloud Manager is moved to a different zone. Then network and storage managers gets stuck and stop doing refresh.

Related to AWS BZ, same issue is for OpenStack:
https://bugzilla.redhat.com/show_bug.cgi?id=1439268

### CODE REVIEW

**Comment by Ladas** [comment]
@miq-bot add_label euwe/yes, fine/yes, bug

**Comment by Ladas** [comment]
@miq-bot assign @tzumainn

**Comment by Ladas** [comment]
@tzumainn could you guys make sure this gets backported correctly?

**Comment by tzumainn** [comment]
Took a moment to figure out where the infra provider's :ensure_managers_zone_and_provider_region's method comes from, but I think I got it!  Looks good, thanks!

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit 4086fa9b2c2ee2e3f9aee8655626c119c0aa8bf1
Author: tzumainn <tzumainn@redhat.com>
Date:   Wed Apr 12 09:45:45 2017 -0400

    Merge pull request #11 from Ladas/ensure_managers_change_zone_and_provider_region_with_cloud_manager
    
    Ensure managers change zone and provider region with cloud manager
    (cherry picked from commit c8fdfb05e34c77d63e31cd0bf0645e59e758644b)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1441740
```

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit 3e2d6945a1f038bcbafa8c7fe1adf978610cfb56
Author: tzumainn <tzumainn@redhat.com>
Date:   Wed Apr 12 09:45:45 2017 -0400

    Merge pull request #11 from Ladas/ensure_managers_change_zone_and_provider_region_with_cloud_manager
    
    Ensure managers change zone and provider region with cloud manager
    (cherry picked from commit c8fdfb05e34c77d63e31cd0bf0645e59e758644b)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1441742
```

**Pull request merged**
