### PR TITLE
Fix Openstack service status section for infra node

### PR DESCRIPTION
**Pull request by andyvesel**
FIX: https://bugzilla.redhat.com/show_bug.cgi?id=1723864
Updated the bash condition which manageiq-ssh-util gem couldn't handle without errors.

### CODE REVIEW

**Comment by chessbyte** [comment]
@agrare should this go back to `jansa`?

**Comment by agrare** [comment]
@andyvesel does this depend on the updated manageiq-ssh-util https://github.com/ManageIQ/manageiq/pull/20128 ?

**Comment by andyvesel** [comment]
@agrare I haven't had any issues on Jansa. Worked for me

**Comment by agrare** [comment]
Must be backported together with https://github.com/ManageIQ/manageiq-providers-openstack/pull/596

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit 263c6913447669f5a3d25c4b074a3ade8fa395c0
Author: Adam Grare <agrare@redhat.com>
Date:   Mon May 18 13:57:50 2020 -0400

    Merge pull request #585 from andyvesel/contanerized_services_fix

    Fix Openstack service status section for infra node

    (cherry picked from commit 9ca71cbb0f3b6ca2b3efe7cc39eb9d6fa989fb08)
```

**Comment by simaishi** [comment]
@andyvesel can this be `ivanchuk/yes`?

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit ed4e5ce07cc26d5efbe926857c158ab75fe90859
Author: Adam Grare <agrare@redhat.com>
Date:   Mon May 18 13:57:50 2020 -0400

    Merge pull request #585 from andyvesel/contanerized_services_fix

    Fix Openstack service status section for infra node

    (cherry picked from commit 9ca71cbb0f3b6ca2b3efe7cc39eb9d6fa989fb08)

    https://bugzilla.redhat.com/show_bug.cgi?id=1723864
```

**Pull request merged**
