### PR TITLE
Adds security group tests

### PR DESCRIPTION
**Pull request by gildub**
Adds `spec/models/manageiq/providers/openstack/network_manager/`
Adds security groups spec file with security group and firewall rules CRUD.

### CODE REVIEW

**Comment by gildub** [comment]
@ladas, 

I can't get pass the `:connect`, seems like there is something happening between the cloud and network providers.

Maybe you'd have a clue.

Cheers,
Gilles

**Comment by gildub** [comment]
@miq-bot assign @Ladas

**Comment by Ladas** [comment]
@gildub hm, try to use ems.network_manager. You might need that for the find I think. The connect could be mocked on either, since network manager delegates that call to the cloud_manager. But all network models are associated with the network manager.

**Comment by gildub** [comment]
@Ladas, I figured it out, I was using ems.network_manager but used the instance instead of the class :(
Thanks.

**Comment by gildub** [comment]
@aufi, @Ladas could you please review?

**Comment by Ladas** [comment]
looks great 👍

**Comment by aufi** [comment]
Yep, looks great to me too, ready to merge when WIP label is removed.

**Comment by gildub** [comment]
@Ladas, @aufi, Thanks.

**Pull request merged**
