### PR TITLE
Add Openstack CinderManager EventCatcher

### PR DESCRIPTION
**Pull request by mansam**

### CODE REVIEW

**Comment by mansam** [comment]
@aufi please review when you can, this is part of the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1570965

**Comment by JPrause** [comment]
..can you also add the fine/yes label.

**Comment by JPrause** [comment]
@Ladas since this is a blocker PR, can you review asap. We have a build coming up and are trying to get these blocker PRs merged.

**Comment by mansam** [comment]
@Ladas There wasn't as far as I could tell from the list of workers. I'd very much like to refactor down to a single event catcher when we've got a little more time to breathe. :)

**Comment by simaishi** [comment]
@mansam Yet another conflict on VCRs... I assume you'd need to create a separate PR for Gaprindashvili?

**Comment by mansam** [comment]
@simaishi Yes, if you're running into a VCR conflict I'll have to make a new PR.

**Comment by simaishi** [comment]
Backported to Gaprindashvili via https://github.com/ManageIQ/manageiq-providers-openstack/pull/283

**Pull request merged**
