### PR TITLE
Delay load qpid_proton via extracted method

### PR DESCRIPTION
**Pull request by chessbyte**
Fixes https://github.com/ManageIQ/manageiq-providers-openstack/issues/601

### CODE REVIEW

**Comment by Fryguy** [comment]
There are 3 places that require qpid_proton and they'd all have to be changed...I updated the issue with them.

**Comment by Fryguy** [comment]
Though I think maybe you can just remove the requires in those files as I see nothing qpid_proton specific (unless specs need it?)

**Comment by Fryguy** [comment]
wonder if we can test this somehow... like a cross repo test, but somehow set BUNDLE_WITHOUT qpid-proton ?

**Comment by chessbyte** [comment]
The [OpenStackStfEventReceiver](https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/lib/manageiq/providers/openstack/legacy/events/openstack_stf_event_receiver.rb) class inherits from `Qpid::Proton::MessagingHandler`, so probably needs the require (although maybe it can be narrower).

**Comment by agrare** [comment]
If you delay require these two:
```
require 'manageiq/providers/openstack/legacy/events/openstack_stf_event_receiver'
require 'manageiq/providers/openstack/legacy/events/openstack_stf_event_test_receiver'
```
that looks like it fixes this

**Comment by chessbyte** [comment]
@agrare should I do the same delay load for the [bunny](https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/lib/manageiq/providers/openstack/legacy/events/openstack_rabbit_event_monitor.rb#L3) gem?

**Comment by agrare** [comment]
@chessbyte Lets leave it for now so we can get this fixed

**Comment by aufi** [comment]
Thanks for the PR :+1:

**Pull request merged**
