### PR TITLE
Friendly error message for HTTP 503

### PR DESCRIPTION
**Pull request by slemrmartin**
Handling HTML error responses from undercloud

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1566570
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1510769

- [x] **Follows PR**: https://github.com/ManageIQ/manageiq-providers-openstack/pull/264

---
Steps to reproduce:

> In our Setup we usually use a deployment of 3 controllers and 2 compute nodes.
> You need to login from undercloud to each controller and stop below services:

```
neutron-dhcp-agent.service                                           
neutron-openvswitch-agent.service                                               
neutron-server.service
```

In **Networks -> Networks**:

1. Click **Configure** / **Add a new Cloud Network**
2. Choose Network manager of unavailable provider (_OpenStack_ / _Ovirt_ only)
3. Fill required fields and click **Add**

---

**Actual results**: 
`unexpected token at '<html><body><h1>503 Service Unavailable</h1> No server is available to handle this request. </body></html> '`

**Expected results**:
`503 Service Unavailable No server is available to handle this request.`

---

@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

Cc @ladas, @aufi

### CODE REVIEW

**Comment by mansam** [comment]
Looks pretty good to me. Have you tested it to ensure it works?

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot remove_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by slemrmartin** [comment]
@mansam Yes, I have. It was the hardest part to get credentials to this environment :)

**Comment by mansam** [comment]
@slemrmartin thanks!

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit a8b9d0b4cdacd837b03dc3589abcade2dfd5def3
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Mon May 21 16:28:40 2018 -0400

    Merge pull request #293 from slemrmartin/neutron-svc-off-message
    
    Friendly error message for HTTP 503
    (cherry picked from commit 1afb38fd3b275826d3d88a16796c70b951b9f5c6)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1566570
```

**Pull request merged**
