### PR TITLE
Bump fog-openstack to version 0.1.27

### PR DESCRIPTION
**Pull request by gildub**
Also fixes vcr cassettes to work with fog-openstack 0.1.27 because of redudant `/` in Compute which was fixed by https://github.com/fog/fog-openstack/commit/19fff350b3d5af3f7108da7bbc4bc8b8463aebfa

Required to support:
https://bugzilla.redhat.com/show_bug.cgi?id=1596320
https://bugzilla.redhat.com/show_bug.cgi?id=1589766

### CODE REVIEW

**Comment by Ladas** [comment]
@gildub that looks like a relevant CI failure. Only Liberty failed?

**Comment by gildub** [comment]
@Ladas, I fixed it, see description for the details.

**Comment by gildub** [comment]
@miq-bot add_label bug

**Comment by gildub** [comment]
Tested with Gaprindashvili

@miq-bot add_label gaprindashvili/yes

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by simaishi** [comment]
@gildub All the spec files are conflicting on backport. Can you please create a separate PR for Gaprindashvili branch?

**Comment by gildub** [comment]
@simaishi, no worries, I´ve added PR#321. Thanks.

**Comment by simaishi** [comment]
Backported to Gaprindashvili via https://github.com/ManageIQ/manageiq-providers-openstack/pull/321

**Pull request merged**
