### PR TITLE
Parse OpenStack Event Timestamps as UTC

### PR DESCRIPTION
**Pull request by aufi**
Timestamps returned in Events from Ceilometer/Panko service don't
contain Timezone information, but OpenStack expects it to use UTC [1].

It should be parsed as UTC to ensure it will not be considered as MIQ machine
local Timezone which could break time-based OpenStack Event queries.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1692892

[1] https://specs.openstack.org/openstack/api-wg/guidelines/time.html

### CODE REVIEW

**Comment by aufi** [comment]
WIP is there just until this will be tested on environment where this issue was discovered, the code is considered to be final (if it works).

**Comment by aufi** [comment]
Works for me locally and on reporter environment (UTC-4), removing WIP.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 6593995dcbb1c3f5dde573800740f35d0024bf77
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Fri Mar 29 11:44:18 2019 -0400

    Merge pull request #457 from aufi/event_timezone_utc
    
    Parse OpenStack Event Timestamps as UTC
    
    (cherry picked from commit 715a5eda99bcfa62bb6ecbe340e1df149efc3f2f)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1694190
```

**Comment by aufi** [comment]
Should be backported to G-branch as fix for https://bugzilla.redhat.com/show_bug.cgi?id=1712049

**Pull request merged**
