### PR TITLE
Make sure volume template has name

### PR DESCRIPTION
**Pull request by Ladas**
Make sure volume template has name

Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1510067

### CODE REVIEW

**Comment by Ladas** [comment]
@mansam I haven't checked the old refresh, we might need same fix there

**Comment by agrare** [comment]
I don't see volume_template parsing for non-graph refresh, @mansam is this expected or was it an oversight?

**Comment by mansam** [comment]
@agrare That's deliberately only being supported on the graph refresh system.

**Comment by agrare** [comment]
Thanks @mansam :+1: to this then

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 8398a57d9e6fef9fa10efd243dc71be4039bec9b
Author: Samuel Lucidi <mansam@csh.rit.edu>
Date:   Thu Nov 9 10:05:49 2017 -0500

    Merge pull request #148 from Ladas/make_sure_volume_template_do_not_have_blank_name
    
    Make sure volume template has name
    (cherry picked from commit 5a99b6f3bdd088e5ab61c1cfef551e7822ecd67a)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1511083
```

**Pull request merged**
