### PR TITLE
[Changelog] Update for Hammer-9

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
@JPrause The header says `Hammer-8`

**Comment by simaishi** [comment]
I fixed the header in the backport.  @JPrause please fix in master when you do changelog next time.

Hammer backport details:

```
$ git log -1
commit f74d1d884be51bd09627718931b42550af64a2b4
Author: Marek Aufart <maufart@redhat.com>
Date:   Fri Jul 19 16:48:03 2019 +0200

    Merge pull request #486 from JPrause/hammer9_cl
    
    [Changelog] Update for Hammer-9
    
    (cherry picked from commit 8de708614ef9959c73ef1fb7cc2b769f73fb3a4b)
```

**Comment by JPrause** [comment]
@simaishi okay, will do.

**Pull request merged**
