### PR TITLE
[WIP] Validate presence of ems_id for vnfd template

### PR DESCRIPTION
**Pull request by Ladas**
Validate presence of ems_id for vnfd template

Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1437640

### CODE REVIEW

**Comment by Ladas** [comment]
before 
screenshot from 2017-03-30 11_29_00 1

after:
screenshot from 2017-11-15 10-12-12

**Comment by Ladas** [comment]
@martinpovolny @mzazrivec where do I set a translation for :ems_id field, now it translates as Ems, I want it as a Provider

Seems like the usual way is putting this in controller though, which is horrible https://github.com/Ladas/manageiq-ui-classic/blob/5c6903b88e26c538192972bbc28719267d41d4d7/app/controllers/catalog_controller.rb#L1105

But is that because we can't set the correct translation using model validations?

**Comment by mzazrivec** [comment]
@Ladas look into `locale/en.yml`, `activerecord.attributes` subtree.

**Comment by Ladas** [comment]
@mzazrivec ah, thanks, I must be blind I would swear that file was empty when I checked it :-)

**Comment by mansam** [comment]
@Ladas does this need any other changes or is it ready to merge?

**Comment by Ladas** [comment]
@mansam I haven't figured out the locale string I need to set, but that will be a core PR. Lets probably wait till I push that, so I don't forget. :-)

**Comment by mansam** [comment]
@Ladas sounds good :)

**Pull request closed without merging**
