### PR TITLE
Prevent iteration over all tenants when picking default tenant

### PR DESCRIPTION
**Pull request by tzumainn**
https://bugzilla.redhat.com/show_bug.cgi?id=1451122
https://bugzilla.redhat.com/show_bug.cgi?id=1469306

### CODE REVIEW

**Comment by mansam** [comment]
Nice! This should help immensely. You need to make sure your vcr cassettes are obfuscated though :)

**Comment by mansam** [comment]
LGTM! :+1: :rocket: :100:

**Comment by simaishi** [comment]
@tzumainn I tried to backport this, but it's a bit complicated... I can backport `handle.rb` to `manageiq-gems-pending`, but the spec files live in `manageiq` repo. Backporting spec files to `manageiq` repo gives conflict on all files, so that will need a separate PR. Once the spec PR is ready, I can backport `handle.rb` so they can go together (not sure if it should go in certain order, or Travis will fail anyway on one until the other gets in?)

**Comment by tzumainn** [comment]
Travis will almost definitely fail until they both go in. I'll regenerate the vcr cassettes for the FINE branch and submit - thanks!

**Comment by tzumainn** [comment]
@simaishi looks like the tests pass for https://github.com/ManageIQ/manageiq-gems-pending/pull/238 without need for updated spec tests, so we don't need to re-record the VCR cassettes, and that one PR is enough for a backport.

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq-gems-pending/pull/238

**Comment by simaishi** [comment]
@tzumainn Can you create Euwe PR for this too?

**Comment by tzumainn** [comment]
@simaishi Oh yeah! Should be ready here: https://github.com/ManageIQ/manageiq/pull/15656

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq/pull/15656

**Pull request merged**
