### PR TITLE
Update provision requirements check to allow exact matches

### PR DESCRIPTION
**Pull request by tzumainn**
https://bugzilla.redhat.com/show_bug.cgi?id=1472420

### CODE REVIEW

**Comment by tzumainn** [comment]
@gmcculloug Do you think updating the provisioning requirements check like this is okay?

**Comment by gmcculloug** [comment]
@tzumainn Yes, I think you want the minimum flavor to be included in the list, where it is skipped today.

@bdunne made the initial change here, maybe he recalls if there was a reason to use `<=` in the condition.

**Comment by aufi** [comment]
Looks good to me, merging.

Anyway it would be great if @bdunne put his ack on this change too.

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit b82ee02ee90afa931746acfb7a90251801f82622
Author: Marek Aufart <aufi.cz@gmail.com>
Date:   Mon Aug 14 15:57:44 2017 +0200

    Merge pull request #72 from tzumainn/provision-check-update
    
    Update provision requirements check to allow exact matches
    (cherry picked from commit 48424c966ddbd2e58b536d4fa239a40466e8280f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1481449
```

**Pull request merged**
