### PR TITLE
Don't collect storage/objects in the InfraManager

### PR DESCRIPTION
**Pull request by agrare**
We don't need to connect to the storage service nor collect objects in the InfraManager

Depends on: ~~https://github.com/ManageIQ/manageiq-providers-openstack/pull/564~~

### CODE REVIEW

**Comment by aufi** [comment]
Just for clarification - @agrare why the Infra Images are not needed? On OpenStack Undercloud there are Images for provisioning baremetals and such images are not part of Storage AFAIK and should be visible in MIQ.

**Comment by agrare** [comment]
Ah sorry not images, I meant objects thanks @aufi I'll correct the title

**Comment by aufi** [comment]
Thanks, looks and works good, merging :+1:

**Comment by agrare** [comment]
Thanks @aufi !

**Pull request merged**
