### PR TITLE
Exporting Strings

### PR DESCRIPTION
**Pull request by MelsHyrule**
Some string here that are visible in the UI were not being exported correctly and as such were not being translated.

## BEFORE
Screen Shot 2022-06-13 at 4 30 38 PM

## AFTER

Screen Shot 2022-06-13 at 4 40 05 PM

@miq-bot add-reviewer @Fryguy
@miq-bot add-reviewer @jrafanie
@miq-bot add-reviewer @jaywcarman 
@miq-bot assign @jrafanie

### CODE REVIEW

**Comment by jaywcarman** [comment]
But wait, there's more! 😄 The OpenStack plugin also has an infra provider with the same fields:
https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/infra_manager.rb#L136
https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/infra_manager.rb#L144
https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/infra_manager.rb#L223
https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/infra_manager.rb#L231

**Comment by jrafanie** [comment]
Kicking tests

**Review by jrafanie — APPROVED** [review]
LGTM

**Comment by Fryguy** [comment]
Backported to `najdorf` in commit afeb6ac6477531093fc5d42992d70c294b75c1d8.

```text
commit afeb6ac6477531093fc5d42992d70c294b75c1d8
Author: Joe Rafaniello <jrafanie@users.noreply.github.com>
Date:   Tue Jun 14 10:02:03 2022 -0400

    Merge pull request #802 from MelsHyrule/exporting-strings
    
    (cherry picked from commit 5b0588308fffa5ad3b4dc02200029a6f811942a2)
```

**Pull request merged**
