### PR TITLE
Infra Discovery: support for SSL

### PR DESCRIPTION
**Pull request by gildub**
Adds discovery of ssl ports
Adds default ironic ssl port

https://bugzilla.redhat.com/show_bug.cgi?id=1212947

### CODE REVIEW

**Comment by gildub** [comment]
@miq-bot add_label enhancement

**Comment by gildub** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by gildub** [comment]
@miq-bot add_reviewer @aufi

**Comment by gildub** [comment]
@miq-bot add_reviewer @sseago

**Comment by aufi** [comment]
Looks good to me, merging!

**Pull request merged**
