### PR TITLE
Moving Inventory Builder functionality to Inventory

### PR DESCRIPTION
**Pull request by slemrmartin**
common functionality extracted to ManageIQ::Providers::Inventory

- [x] depends on https://github.com/ManageIQ/manageiq/pull/17907
- [x] depends on https://github.com/ManageIQ/manageiq/pull/17942

### CODE REVIEW

**Comment by slemrmartin** [comment]
cc @agrare @Ladas

**Comment by slemrmartin** [comment]
Hello @mansam, that's because of unifying namespaces.
Manager has class ManageIQ::Providers::Openstack::**StorageManager::CinderManager**,
so automatic derivation from core is ManageIQ::Providers::Openstack::Inventory::Collector::**StorageManager::CinderManager** not Collector::CinderManager.

it's the same like Amazon's S3 and Ebs Storage managers.

**Comment by mansam** [comment]
@slemrmartin Thanks for the response. That's an understandable goal, but please try to put unrelated changesets in different PRs in the future.

**Comment by slemrmartin** [comment]
@mansam this is related change - it was necessary to use `Inventory` functions written in core - see dependency and keep openstack's `Inventory` class small, otherwise these collector/persister/parser classes have to be defined manually

**Comment by mansam** [comment]
@slemrmartin Ah, I see. Thanks!

**Pull request merged**
