### PR TITLE
Add flavors info in instance provisioning

### PR DESCRIPTION
**Pull request by alexander-demichev**
Flavors info when selecting flavor in instance provisioning.

screen shot 2017-09-06 at 14 39 44

### CODE REVIEW

**Comment by tzumainn** [comment]
Hi! It looks like the tests need to be updated. I'm also not seeing the updated descriptions, am I missing a patch?

**Comment by aufi** [comment]
Works for me

**Comment by tzumainn** [comment]
In that case, I think this can be merged once the tests are done being updated!

**Comment by tzumainn** [comment]
Okay, I fixed my environment, and this works for me as well. Thanks!

**Pull request merged**
