### PR TITLE
Fix tenant associations on VolumeSnapshotTemplates

### PR DESCRIPTION
**Pull request by mansam**
Found and fixed two issues: one was that if a volume snapshot was available but the volume it was based on wasn't available at the time of refresh, that volume wouldn't be collected. The other issue is that the inventory parser was trying to read the wrong field to collect the tenant, and as such wasn't finding one. This was causing VolumeSnapshotTemplates to appear visible to all tenants.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1589028

### CODE REVIEW

**Comment by aufi** [comment]
Thanks @mansam for the fix! Looks good to me, merging :+1:

**Comment by simaishi** [comment]
@mansam Most of the vcr cassettes conflict backporting to Gaprindashvili branch. Please create a separate PR.

**Comment by mansam** [comment]
@simaishi will do

**Comment by simaishi** [comment]
Backported to Gaprindashvili via https://github.com/ManageIQ/manageiq-providers-openstack/pull/312

**Pull request merged**
