### PR TITLE
[HAMMER] Bumps fog-openstack to v0.1.28

### PR DESCRIPTION
**Pull request by gildub**
https://bugzilla.redhat.com/show_bug.cgi?id=1624840
https://bugzilla.redhat.com/show_bug.cgi?id=1608230

### CODE REVIEW

**Comment by gildub** [comment]
@agrare, sorry I'm not following you? This is manageiq-providers-openstack.

**Comment by agrare** [comment]
Yeah sorry I meant gems-pending

**Comment by gildub** [comment]
That's what I thought. 
No need to update manageiq-gems-pending because it has a loose dependency `~> 0.3`.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 5ae188343f92657016dd724b79e89df82f2e6198
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Fri Nov 2 09:46:02 2018 -0400

    Merge pull request #387 from gildub/hammer_bump_fog-openstack
    
    [HAMMER] Bumps fog-openstack to v0.1.28
    
    (cherry picked from commit 49f5b12890fa77c651a54b18638ed449cb223bb6)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1648674
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653417
```

**Pull request merged**
