### PR TITLE
Remove unused NetworkManager::MetricsCapture

### PR DESCRIPTION
**Pull request by kbrock**
This is more of a place holder for a conversation.

I'm pretty sure that metrics capture does not work for the network manager.

It doesn't look like it can be called since `capture_ems_targets` only returns values for Container, Cloud, or Infra managers.

There is a worker focused on collecting NetworkManager metrics.
Not sure if I got all the classes necessary here

### CODE REVIEW

**Comment by agrare** [comment]
:+1: looks good @kbrock can you rebase?

**Comment by aufi** [comment]
:+1:

**Comment by jrafanie** [comment]
Looks like this is causing ovirt provider to failed to load

See: https://github.com/ManageIQ/manageiq-ui-classic/pull/6650#issuecomment-582095661

```
irb(main):009:0> ManageIQ::Providers::Redhat::NetworkManager::EventCatcher
Traceback (most recent call last):
       16: from thor (1.0.1) lib/thor/command.rb:27:in `run'
       15: from railties (5.2.4.1) lib/rails/commands/console/console_command.rb:96:in `perform'
       14: from railties (5.2.4.1) lib/rails/commands/console/console_command.rb:19:in `start'
       13: from railties (5.2.4.1) lib/rails/commands/console/console_command.rb:64:in `start'
       12: from (irb):9
       11: from (irb):9:in `rescue in irb_binding'
       10: from activesupport (5.2.4.1) lib/active_support/dependencies/interlock.rb:13:in `loading'
        9: from activesupport (5.2.4.1) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        8: from activesupport (5.2.4.1) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        7: from /Users/joerafaniello/.gem/ruby/2.6.5/bundler/gems/manageiq-providers-ovirt-ea421fd0a2df/app/models/manageiq/providers/redhat/network_manager.rb:1:in `<top (required)>'
        6: from /Users/joerafaniello/.gem/ruby/2.6.5/bundler/gems/manageiq-providers-ovirt-ea421fd0a2df/app/models/manageiq/providers/redhat/network_manager.rb:7:in `<class:NetworkManager>'
        5: from lib/extensions/require_nested.rb:12:in `require_nested'
        4: from activesupport (5.2.4.1) lib/active_support/dependencies/interlock.rb:13:in `loading'
        3: from activesupport (5.2.4.1) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        2: from activesupport (5.2.4.1) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        1: from /Users/joerafaniello/.gem/ruby/2.6.5/bundler/gems/manageiq-providers-ovirt-ea421fd0a2df/app/models/manageiq/providers/redhat/network_manager/metrics_capture.rb:1:in `<top (required)>'
NameError (uninitialized constant ManageIQ::Providers::Openstack::NetworkManager::MetricsCapture)
```

**Comment by jrafanie** [comment]
It's failing because the deleted class here was used by the ovirt provider here:  https://github.com/ManageIQ/manageiq-providers-ovirt/blob/master/app/models/manageiq/providers/redhat/network_manager/metrics_capture.rb#L1

**Comment by agrare** [comment]
If the Openstack::NetworkManager::MetricsCapture class was pointelss, we should be able to delete the Ovirt subclass also

**Comment by jrafanie** [comment]
> If the Openstack::NetworkManager::MetricsCapture class was pointelss, we should be able to delete the Ovirt subclass also

I like the way you think.

:fire: 🗑 🚽 

@kbrock more deletions...

**Pull request merged**
