### PR TITLE
Make events_backread switchable

### PR DESCRIPTION
**Pull request by aufi**
OpenStack should expect timestamps in UTC. However some production environments
might work in different way. The safest way fix seems to be extend event_backread
feature with possibility to turn it off.

Event backread can be now turned off by setting :event_backread_seconds
settings option to number less than 1, e.g. 0.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1734338

### CODE REVIEW

**Comment by aufi** [comment]
@Ladas There was problem with intepretation time with timezones between CF and OSP, disabling backread avoids timestamp manipulation on CF side.

**Comment by simaishi** [comment]
@aufi `ivanchuk/yes` and `hammer/yes`?

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 3c5e6758acb97de1fcdd9b3043e72c2f2094541d
Author: Ladislav Smola <lsmola@redhat.com>
Date:   Thu Aug 8 10:59:31 2019 +0200

    Merge pull request #491 from aufi/events_backread_switch
    
    Make events_backread switchable
    
    (cherry picked from commit a600714cdcfd7617a69102eae86fdbe1c28178b0)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1734338
```

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit aac58975f132d2d58a87748a6b2c09ecfa11304f
Author: Ladislav Smola <lsmola@redhat.com>
Date:   Thu Aug 8 10:59:31 2019 +0200

    Merge pull request #491 from aufi/events_backread_switch
    
    Make events_backread switchable
    
    (cherry picked from commit a600714cdcfd7617a69102eae86fdbe1c28178b0)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740767
```

**Pull request merged**
