### PR TITLE
Update client to use renamed NetworkDiscovery

### PR DESCRIPTION
**Pull request by jrafanie**
https://github.com/ManageIQ/manageiq/pull/16994

Add missing test for the probe method.

### CODE REVIEW

**Comment by gildub** [comment]
@jrafanie, I missed this PR as I didn't check the ongoing PRs. Anyway I wished you had mentioned it in the related change or issue. Anyway the `require` needs to be updated too per now closed https://github.com/ManageIQ/manageiq-providers-openstack/pull/229

**Comment by gildub** [comment]
@bdunne, please review.

**Comment by bdunne** [comment]
@agrare Can you take a look at this one too?

**Comment by gildub** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 532cafb0c6e66556464cc38837f9c199d578af8d
Author: Adam Grare <agrare@redhat.com>
Date:   Wed Feb 21 09:44:12 2018 -0500

    Merge pull request #227 from jrafanie/rename_manageiq_network_to_network_discovery
    
    Update client to use renamed NetworkDiscovery
    (cherry picked from commit b43511485ba9e2ee40e655a6d2cc60f0957fcd95)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1552665

```

**Pull request merged**
